package models

import "gorm.io/gorm"

// Prescription is generated by either an OPD consultation or an Admission.
// Exactly one of ConsultationID or AdmissionID will be set.
type Prescription struct {
	gorm.Model
	ConsultationID *uint  `gorm:"column:consultation_id" json:"consultation_id"`
	AdmissionID    *uint  `gorm:"column:admission_id" json:"admission_id"`
	PrescribedBy   uint   `gorm:"column:prescribed_by;not null" json:"prescribed_by"` // Doctor ID
	Notes          string `gorm:"column:notes;type:text" json:"notes"`

	// Relationships
	Consultation *OPDConsultation `gorm:"foreignKey:ConsultationID" json:"consultation,omitempty"`
	Admission    *Admission       `gorm:"foreignKey:AdmissionID" json:"admission,omitempty"`
	Dispenses    []PharmacyDispense `gorm:"foreignKey:PrescriptionID" json:"dispenses,omitempty"`
}

func (Prescription) TableName() string {
	return "hc_prescriptions"
}
